version: '3'

services:
  postgres:
    image: postgres
    restart: always
    hostname: postgres
    volumes:
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

    environment:
      - POSTGRES_PASSWORD=password!
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=pokemon-api
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 2s
      retries: 30