CREATE TABLE pokemons (
  "id" SERIAL PRIMARY KEY UNIQUE NOT NULL,
  "name" VARCHAR(100) NOT NULL,
  "pokedex_number" INT NOT NULL,
  "img_name" VARCHAR(255),
  "generation" INT,
  "evolution_stage" VARCHAR(100),
  "evolved" INT,
  "family_id" INT,
  "cross_gen" INT,
  "type_one" VARCHAR(100),
  "type_two" VARCHAR(100),
  "weather_one" VARCHAR(100),
  "weather_two" VARCHAR(100),
  "stat_total" INT,
  "atk" INT,
  "def" INT,
  "sta" INT,
  "legendary" INT,
  "aquireable" INT,
  "spawns" INT,
  "regional" INT,
  "raidable" INT,
  "hatchable" INT,
  "shiny" INT,
  "nest" INT,
  "new" INT,
  "not_gettable" INT,
  "future_evolve" INT
)